---
- name: Install packages
  become: yes
  package:
    update_cache: true
    name: "{{ webserver_packages }}"
    state: latest

- name: Turn off apache
  become: yes
  ansible.builtin.service:
    name: apache2
    state: stopped

- name: Add base NGINX configuration file
  become: yes
  copy:
    dest: /etc/nginx/nginx.conf
    src: etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload NGINX

- name: Clone git repositories
  git:
    repo: "{{ item.repository}}"
    dest: "{{ item.root }}"
    force: yes
  with_items: "{{ webserver_static_sites }}"

- name: Add static site config files
  become: yes
  template:
    src: etc/nginx/conf.d/site.conf.j2
    dest: "/etc/nginx/conf.d/{{ item.name }}.conf"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ webserver_static_sites }}"
  notify: Reload NGINX

- name: Download/Extract Hugo if not exists
  unarchive:
    src: https://github.com/gohugoio/hugo/releases/download/v0.134.2/hugo_0.134.2_linux-amd64.tar.gz
    dest: "{{ item.root }}"
    creates: "{{item.root}}/hugo"
    remote_src: true
  with_items: "{{ webserver_static_sites }}"

- name: Create self-signed certificate, if configured.
  command: openssl req -x509 -nodes -subj '/CN={{ vagrant_hostname }}' -days 365 -newkey ed25519 -sha256 -keyout {{ item.key }} -out {{ item.cert }}
    creates={{ item.cert }}
  with_items: "{{ self_signed_certs }}"
  
# - name: Create /etc/ssl/private for the private ssl key
#   become: true
#   ansible.builtin.file:
#     path: /etc/ssl/private
#     state: directory
#     mode: 700
  
# - name: Create private key (X25519) with password protection
#   become: true
#   community.crypto.openssl_privatekey:
#     path: /etc/ssl/private/selfsigned_private.key
#     type: Ed25519
#     cipher: auto
#     passphrase: changeme
#   
# - name: Create a self signed cert if not exists
#   become: true
#   community.crypto.x509_certificate:
#     path: /etc/ssl/certs/selfsigned.pem
#     privatekey_path: /etc/ssl/certs/selfsigned.key
#     provider: selfsigned
#     privatekey_passphrase: changeme
#     privatekey_path: /etc/ssl/private/selfsigned_private.key
#   
